### ISSUE TITLE
rake task (test) not working

### ISSUE THREAD

**Issue by commel** [jruby/activerecord-jdbc-adapter#309]
I am using JRuby 1.7.2 with Oracle Java 1.7.0_11. My Gemfile.lock says I am using:
- activerecord-jdbc-adapter (1.2.5)
- activerecord-jdbchsqldb-adapter (1.2.5)

and whant to run my tests via rake and rspec:

```
    comrad@comrad-laptop:~/Entwicklung/holarse$ rake test
```

This results in the error:

```
    Errors running test:units! #<RuntimeError: Task not supported by 'jdbc'>
```

Here is my database.yml:

``` YAML
    test:
      adapter: jdbc
      driver: org.hsqldb.jdbcDriver
      url: jdbc:hsqldb:file:/tmp/holarse/test
      username: SA
      password:
```

Google told me that this problem seem to be fixed with AR 0.9.2. So now i am confused.
