### ISSUE TITLE
rake db:create does not work (derby)

### ISSUE THREAD

**Issue by rweng** [jruby/activerecord-jdbc-adapter#344]
Hi, when running `rake db:create:all` nothing at all happens. Return code is 0 though. Any ideas how to debug this? I tried `rake -v`, but that doesn't change a thing.

Here's my `database.yml`:

```
development:
  adapter: jdbc
  driver: org.apache.derby.jdbc.EmbeddedDriver
  username: app
  password: app
  url: jdbc:derby:db/derby/test;create=true

test:
  adapter: jdbc
  driver: org.apache.derby.jdbc.EmbeddedDriver
  username: app
  password: app
  url: jdbc:derby:db/derby/test;create=true

production:
  adapter: jdbc
  driver: org.apache.derby.jdbc.EmbeddedDriver
  username: app
  password: app
  url: jdbc:derby:db/derby/prod;create=true
```
