### ISSUE TITLE
mssql adapter with sql server 2008 [sqljdbc driver]

### ISSUE THREAD

**Issue by kevinsheffield** [jruby/activerecord-jdbc-adapter#411]
For brevity, I made a new project, added a Post scaffold with 2 string and 1 text fields. I receive the following error when I try to run rake db:migrate on a sql server 2008 database

```
rake aborted!
unable to choose type for timestamp from:
["datetime2", "datetime"]
org/jruby/RubyArray.java:1617:in `each'
arjdbc/jdbc/RubyJdbcConnection.java:775:in `set_native_database_types'
org/jruby/RubyBasicObject.java:1709:in `__send__'
org/jruby/RubyKernel.java:2213:in `send'
org/jruby/RubyProc.java:255:in `call'
org/jruby/RubyArray.java:1617:in `each'
org/jruby/RubyArray.java:1617:in `each'
org/jruby/RubyKernel.java:1073:in `load'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Here is the pertinent gemfile lines....

```
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0.rc2'

# Use jdbcsqlite3 as the database for Active Record
gem 'activerecord-jdbcmssql-adapter', :github => 'jruby/activerecord-jdbc-adapter'
```

I am using jruby 1.7.4

```
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_45-b06-451-11M4406 [darwin-x86_64]
```

And here is the database.yml

```
development:
  adapter: jdbcmssql
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  host: host name
  url: 'jdbc:sqlserver://host name: port;databaseName=db name'
  username: user
  password: pass
  port: port
```

I will comment with the full db:migrate trace
