### ISSUE TITLE
ability for fine graimned prepared_statement configuration

### ISSUE THREAD

**Issue by kares** [jruby/activerecord-jdbc-adapter#507]
```
prepared_statements:
  - exec_query: true
  - exec_insert: false
  - internal: false
```
##
