### ISSUE TITLE
MySQL Connector/J multi-host helpers

### ISSUE THREAD

**Issue by kares** [jruby/activerecord-jdbc-adapter#659]
... since multi-hosts might be used for replication/loadbalancing (besides fail-over).

so that users do not have to specify the full jdbc syntax we should introduce : 
```yaml
adapter: mysql
  host: host1,host2
  loadbalance: true # jdbc:mysql:replication://[master host][:port],[slave host 1][:port] ...
  # replication: true # jdbc:mysql:loadbalance://[host1][:port],[host2][:port][,[host3][:port]]...
```
