### ISSUE TITLE
connection_alive_timeout should have default value

### ISSUE THREAD

**Issue by dgolombek** [jruby/activerecord-jdbc-adapter#778]
A server of ours locked up because this undocumented value defaults to 0, leading to unbounded blocking calls when our DB went away behind us, despite having all of the documented ActiveRecord and MySQL timeouts configured.

A deeper explanation:
 ActiveRecord::ConnectionAdapters::ConnectionPool uses a single Monitor for all of its synchronize calls. When a connection is checked out from that pool, it calls #checkout_and_verify from within a synchronize block, which in turn calls connection#verify, which down the line calls arjdbc.mysql.MySQLRubyJdbcConnection.isConnectionValid(). Since there is no timeout by default, that blocks forever -- while holding the Monitor lock. So now any later call to connection_pool#checkout blocks trying to acquire that lock, with no possibility of timing out based on ConnectionPoll#checkout_timeout

I know that isConnectionValid is used in other places, so it's not clear exactly what default should be -- we could use 5s, same as ConnectionPool, or have it default to properties.socketTimeout if that's set. But I believe we should have a default value here, or at least document this property so that other people don't get stuck on this as well.

**Comment by dgolombek** [comment]
I just noticed that it's looking in @config for the value of connection_alive_timeout, so in that case I think it makes more sense to default to the value of @config['read_timeout'].

**Comment by kares** [comment]
its just how AR's pool works. not sure an isValid default timeout will change for one adapter. you understood the consequences and acted accordingly. how would one configure a read_timeout while wanting the isValid() behavior - think it might make sense with some cloudy setups ...

**Comment by dgolombek** [comment]
At the very least, we should have documentation of the config variable -- right now, no one knows to configure this value until they get bitten by this failure (and I've seen no writeups of it elsewhere). 

Beyond that, requiring developers to find this in the documentation and configure it separately violates the principle of least astonishment. Developers somewhat expect to have to set connect/read/write timeouts (although they're spoiled by having default timeouts elsewhere...),  but having to configure different timeouts differently between JRuby and MRI is surprising. 

It's true that with a ~local DB this is not a big deal, but when you start using a cloud database, this suddenly becomes a big deal (this bit us with AWS RDS).

**Comment by kares** [comment]
documented in the wiki: https://github.com/jruby/activerecord-jdbc-adapter/wiki/Configuration

**Comment by mohamedhafez** [comment]
@dgolombek how were you able to end up setting `connection_alive_timeout`? I tried setting it in my database.yml as below, but every time I try to do a reboot with failover on AWS RDS, it still just hangs forever

```yaml
production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: mydb
  pool: 10
  username: web
  password: xxx
  host: database-1.xxx.us-east-1.rds.amazonaws.com
  read_timeout: 30
  write_timeout: 30
  connect_timeout: 30
  connection_alive_timeout: 5
  properties: { useSSL: false, serverTimezone: "America/Los_Angeles" }
```

**Comment by dgolombek** [comment]
For a variety of historical and configuration reasons, we build our connection via ActiveRecord::Base.establish_connection directly, instead of via Rails+AR magic. Within that context, this flag was working for me when I last tested it. 

This is actually a good reminder that I haven't run a zone failure test this year, or encountered one naturally, so I can't promise that it works with newest incarnation of gems. It worked last year. Adds to todo list...

**Comment by mohamedhafez** [comment]
For anybody else that stumbles upon this page, I got this to work by setting `connectTimeout` and `socketTimeout` in the `properties` hash below (why `write_timeout`, `read_timeout`, and `connect_timeout` aren't working I don't know)

```yaml
production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: mydb
  pool: 10
  username: web
  password: xxx
  host: database-1.xxx.us-east-1.rds.amazonaws.com
  read_timeout: 30
  write_timeout: 30
  connect_timeout: 30
  connection_alive_timeout: 30
  properties:
    connectTimeout: 30000
    socketTimeout: 30000
    useSSL: false
    serverTimezone: "America/Los_Angeles"
```
