### ISSUE TITLE
Add authenticationScheme support for MSSQL adapter when using official driver

### ISSUE THREAD

**Issue by Ultimation** [jruby/activerecord-jdbc-adapter#814]
This will allow for using windows auth via kerberos on linux machines, 

A work around is to simply specific the path instead of passing the parameters. 

Some more information:
https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server

**Comment by kares** [comment]
if you're using the correct driver, just specify the required `properties: ` under your configuration and it will work
e.g.
```
production:
  adapter: mssql
  properties: 
    authenticationScheme: JavaKerberos
    ...
```
