### ISSUE TITLE
ssl connection issue

### ISSUE THREAD

**Issue by chetanbissa27** [jruby/activerecord-jdbc-adapter#938]
I trying to connect app server to db server with secure connection. I have copied db ssl files to app server and updated following changes in database.yml file.
its giving 

> ActiveRecord::JDBCError: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot open JKS [Invalid keystore format]

```
production:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: production
  pool: 10
  host: IP
  username: root
  password: root
  sslca: /root/certs/ca.pem
  sslkey: /root/certs/client-key.pem
  sslcert: /root/certs/client-cert.pem
  sslcapath: /root/certs/
```
when I am tring from command with following command its working
mysql -u root -p -h <DB-sever-ip> --ssl-capath=/root/certs/ --ssl-ca=/root/certs/ca.pem --ssl-cert=/root/certs/client-cert.pem --ssl-key=/root/certs/client-key.pem
